jshint: 
  enabled: false
eslint:
  enabled: true
  config_file: style/config/.eslintrc.json
  ignore_file: style/config/.eslintignore
tslint:
  enabled: true
  config_file: style/config/tslint.json
ruby:
  enabled: true
  config_file: style/config/.rubocop.yml
scss:
  enabled: true
  config_file: style/config/.scss-lint.yml
